import { CustomerDocumentRenderer } from "./CustomerDocumentRenderer.jsx";
import { customerDocumentMoney, revisionDifference } from "./customer-document-model.js";

export function CustomerDocumentReview({ projection, previousRevision = null, onClose, issueAvailable = false, onIssue, issueLabel = "", issueBusy = false, shareLink = "", onCopyLink, onCreateReplacementGrant, onRefreshResponse, onActivate, activateAvailable = false, activationBusy = false, actionError = "", delivery = null }) {
  const changes = previousRevision ? revisionDifference(previousRevision, projection) : [];
  const isInvoice = projection.type === "invoice";
  const label = isInvoice ? "Invoice" : "Estimate";
  const unavailableLabel = isInvoice ? "Invoice issuance is unavailable until Work done matches the accepted Estimate." : "Estimate issuance is unavailable until the server validates this draft.";
  return <section className="customer-document-review" aria-labelledby="customer-document-preview-title"><div className="customer-document-review-heading"><div><p className="customer-document-kicker">Customer-safe preview</p><h2 id="customer-document-preview-title">{label} preview</h2><p>This preview excludes internal cost and inventory data. Server validation is required before issuance.</p></div>{onClose ? <button type="button" className="button secondary" onClick={onClose}>Close preview</button> : null}</div>{changes.length ? <section className="customer-document-difference" aria-labelledby="customer-document-changes-title"><h3 id="customer-document-changes-title">Changes since approved revision</h3>{changes.map((change) => <p key={change.id}><strong>{change.after?.description || change.before?.description}</strong><span>{customerDocumentMoney(change.before?.amount, projection.currency)} → {customerDocumentMoney(change.after?.amount, projection.currency)}</span></p>)}</section> : null}<CustomerDocumentRenderer projection={projection}/>{projection.response?.status !== "pending" ? <p role="status">Customer response: {projection.response.status.replaceAll("_", " ")}{projection.response.customerName ? ` by ${projection.response.customerName}` : ""}.</p> : null}{actionError ? <p role="alert">{actionError}</p> : null}<div className="customer-document-review-actions">{onIssue ? <button type="button" className="button primary" disabled={!issueAvailable || issueBusy} onClick={onIssue}>{issueBusy ? "Issuing…" : issueAvailable ? issueLabel || `Issue ${label.toLowerCase()}` : unavailableLabel}</button> : null}{shareLink ? <><a className="button secondary" href={shareLink}>Open customer link</a><button type="button" className="button secondary" onClick={onCopyLink}>Copy customer link</button></> : null}{onCreateReplacementGrant ? <button type="button" className="button secondary" disabled={issueBusy} onClick={onCreateReplacementGrant}>Create replacement customer link</button> : null}{projection.revisionId && onRefreshResponse ? <button type="button" className="button secondary" onClick={onRefreshResponse}>Refresh response</button> : null}{activateAvailable ? <button type="button" className="button primary" disabled={activationBusy} onClick={onActivate}>{activationBusy ? "Activating…" : "Activate Workorder"}</button> : null}</div>{delivery}</section>;
}
