import { CurrencySelector } from "../../components/forms/CurrencySelector.jsx";
import { DatePicker } from "../../components/forms/DatePicker.jsx";
import { sendInventoryCommand,inventoryCommandCanBeEdited } from './inventory-command.js';
import { useEffect,useState } from 'react';
import { api } from '../../lib/api.js';
import { Button } from '../../components/ui/Button.jsx';
import { Dropdown } from '../../components/forms/Dropdown.jsx';
import { SecondaryDetailPanel,SecondaryDetailSection } from '../../components/ui/SecondaryDetailPanel.jsx';
export function InventoryBills({locationId,actorId,suppliers=[]}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0),[page,setPage]=useState(1),[selected,setSelected]=useState(null),[creating,setCreating]=useState(false);
 const [supplierId,setSupplierId]=useState(''),[reference,setReference]=useState(''),[currency,setCurrency]=useState('USD'),[subtotal,setSubtotal]=useState(''),[tax,setTax]=useState('0'),[dueDate,setDueDate]=useState(''),[notes,setNotes]=useState('');
 const [amount,setAmount]=useState(''),[evidence,setEvidence]=useState(''),[receiptLineId,setReceiptLineId]=useState(''),[quantity,setQuantity]=useState('');
 const key=`inventory-bill-command:${actorId}:${locationId}`,[pending,setPending]=useState(()=>{try{return JSON.parse(localStorage.getItem(key));}catch{return null;}});
 useEffect(()=>{if(!locationId)return;let active=true;api(`/api/office/inventory/bills?${new URLSearchParams({locationId,page:String(page)})}`).then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[locationId,page,refresh]);
 async function command(body){
  if(busy)return;setBusy(true);setError('');const request=pending||{...body,locationId,idempotencyKey:crypto.randomUUID()};
  try{
   localStorage.setItem(key,JSON.stringify(request));setPending(request);
   const result=await sendInventoryCommand({request,recover:!!pending,url:'/api/office/inventory/bills'});
   localStorage.removeItem(key);setPending(null);setSelected(result.bill);setCreating(false);setRefresh(x=>x+1);setAmount('');setEvidence('');setQuantity('');setReceiptLineId('');
  }catch(e){setError(e.message);if(inventoryCommandCanBeEdited(e)){localStorage.removeItem(key);setPending(null);}}finally{setBusy(false);}
 }
 return <section className="inventory-workflows"><div className="inventory-workflow-toolbar"><h3>Supplier bills</h3><Button onClick={()=>setRefresh(x=>x+1)}>Refresh bills</Button><Button disabled={!!pending} onClick={()=>setCreating(true)}>Record supplier bill</Button></div><p>Record the supplier invoice, link stock receipts already added to inventory, and track what is owed.</p><details className="purchase-bills-help"><summary>How Bills works</summary><ol><li>Record the supplier, invoice reference, subtotal, tax and due date.</li><li>Match the billed quantities to existing stock receipts. A PO marked Received is available to match after you choose Add to inventory.</li><li>An Admin records payment evidence or a supplier credit to reduce the outstanding balance.</li></ol><p>Bills does not add stock or send payments. It records invoices, matching and payment history.</p></details>
  {error?<p role="alert">{error}</p>:null}{pending?<p>A saved bill action needs confirmation. <Button disabled={busy} onClick={()=>command(pending)}>Check saved action</Button></p>:null}
  {creating?<form className="inventory-workflow-form" onSubmit={e=>{e.preventDefault();command({action:'create',supplierId,reference,currency,subtotal,tax,dueDate,notes});}}><h3>Bill details</h3><label>Supplier<Dropdown required value={supplierId} onChange={e=>setSupplierId(e.target.value)}><option value="">Choose supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Dropdown></label><label>Supplier bill reference<input required maxLength={240} value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Currency<CurrencySelector required value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())}/></label><label>Subtotal before tax<input required inputMode="decimal" value={subtotal} onChange={e=>setSubtotal(e.target.value)}/></label><label>Tax amount<input required inputMode="decimal" value={tax} onChange={e=>setTax(e.target.value)}/></label><label>Due date<DatePicker aria-label="Due date" required  value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label><label>Document / review notes<textarea maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="inventory-request-actions"><Button type="button" onClick={()=>setCreating(false)}>Close</Button><Button type="submit" disabled={busy||!!pending}>Confirm bill totals</Button></div></form>:null}
  {data?.outstanding.length?<ul>{data.outstanding.map(s=><li key={s.currency}>{s.currency} outstanding: {s.outstanding} · Overdue: {s.overdue||'0.00'}</li>)}</ul>:null}
  {data?.items.length?<div className="inventory-workflow-list">{data.items.map(b=><button type="button" key={b.id} onClick={()=>setSelected(b)}><strong>{b.reference} · {b.supplier_name}</strong><span>{b.currency} {b.outstanding} outstanding · Due {String(b.due_date).slice(0,10)}</span></button>)}</div>:<p>No supplier bills at this shop.</p>}
  {page>1||data?.hasMore?<div className="inventory-request-actions"><Button disabled={page===1} onClick={()=>setPage(x=>x-1)}>Previous</Button> Page {page} <Button disabled={!data?.hasMore} onClick={()=>setPage(x=>x+1)}>Next</Button></div>:null}
  <SecondaryDetailPanel open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}} title={selected?`Bill ${selected.reference}`:'Bill'} description={selected?.supplier_name||''}>{selected?<div className="inventory-workflows">
   <SecondaryDetailSection title="Money"><p>{selected.currency} · Subtotal {selected.subtotal} · Tax {selected.tax}</p><p>Paid {selected.paid} · Credited {selected.credited} · Outstanding {selected.outstanding}</p><p>{selected.notes}</p>{data?.canRecordMoney&&Number(selected.outstanding)>0?<><label>Amount<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Payment confirmation / supplier credit reference<input value={evidence} maxLength={240} onChange={e=>setEvidence(e.target.value)}/></label><div className="inventory-workflow-toolbar"><Button disabled={busy||!!pending||!amount||!evidence.trim()} onClick={()=>command({action:'payment',billId:selected.id,expectedVersion:selected.version,amount,reference:evidence})}>Record payment evidence</Button><Button disabled={busy||!!pending||!amount||!evidence.trim()} onClick={()=>command({action:'credit',billId:selected.id,expectedVersion:selected.version,amount,reference:evidence})}>Record supplier credit</Button></div></>:null}</SecondaryDetailSection>
   <SecondaryDetailSection title="Match received goods"><p>Matching links goods already received. It does not add stock.</p><ul>{selected.allocations.map(a=><li key={a.receipt_line_id}>{a.part_number} · {a.quantity} {a.uom_code}</li>)}</ul><label>Unmatched receipt<Dropdown value={receiptLineId} onChange={e=>setReceiptLineId(e.target.value)}><option value="">Choose receipt</option>{data?.receipts.map(r=><option key={r.id} value={r.id}>{r.part_number} · {r.unmatched_quantity} {r.uom_code} · {r.source_reference||new Date(r.posted_at).toLocaleDateString()}</option>)}</Dropdown></label><label>Quantity covered by this bill<input type="number" min="0" step="any" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><Button disabled={busy||!!pending||!receiptLineId||!quantity} onClick={()=>command({action:'match',billId:selected.id,expectedVersion:selected.version,allocations:[{receiptLineId,quantity:Number(quantity)}]})}>Match receipt quantity</Button></SecondaryDetailSection>
   {error?<p role="alert">{error}</p>:null}{pending?<Button disabled={busy} onClick={()=>command(pending)}>Check saved action</Button>:null}<SecondaryDetailSection title="History"><ul>{selected.events.map((e,i)=><li key={i}>{e.action} · {e.amount||''} {e.reference} · {new Date(e.created_at).toLocaleString()}</li>)}</ul></SecondaryDetailSection>
  </div>:null}</SecondaryDetailPanel>
 </section>;
}
