import { useEffect, useState } from "react";
import { Dropdown } from "../../components/forms/Dropdown.jsx";
import { Button } from "../../components/ui/Button.jsx";
import { OperationalDataCell, OperationalDataRow, OperationalDataTable } from "../../components/ui/OperationalDataTable.jsx";
import { workorderDetailSearch } from "../../app/routes/route-state.js";
import { api } from "../../lib/api.js";
import "./inventory-tables.css";
import "./inventory-workflows.css";

const STOCK_COLUMNS = [{ id: "part", label: "Part", isRowHeader: true }, { id: "unit", label: "Unit" }, { id: "tracked", label: "Tracked total" }, { id: "held", label: "Held / repair" }, { id: "reserved", label: "Reserved" }, { id: "available", label: "Available" }, { id: "used", label: "Used (30 days)" }];
const COMMITMENT_COLUMNS = [{ id: "currency", label: "Currency", isRowHeader: true }, { id: "priced", label: "Priced commitment" }, { id: "orders", label: "Orders" }, { id: "unpriced", label: "Unpriced lines" }];
const TRANSIT_COLUMNS = [{ id: "part", label: "Part", isRowHeader: true }, { id: "status", label: "Status" }, { id: "moving", label: "In transit" }, { id: "received", label: "Received" }, { id: "exceptions", label: "Exceptions" }, { id: "route", label: "Route" }, { id: "destination", label: "Destination" }, { id: "holder", label: "Holder" }];
const BILL_COLUMNS = [{ id: "currency", label: "Currency", isRowHeader: true }, { id: "outstanding", label: "Outstanding" }, { id: "overdue", label: "Overdue" }];
const CUSTODY_COLUMNS = [{ id: "status", label: "Status", isRowHeader: true }, { id: "age", label: "Age" }, { id: "part", label: "Part / serial" }, { id: "source", label: "Unit / workorder" }, { id: "where", label: "Location / disposition" }, { id: "lineage", label: "Purchase record" }];
const RECONCILIATION_COLUMNS = [{ id: "status", label: "Status", isRowHeader: true }, { id: "scope", label: "Scope" }, { id: "difference", label: "Difference" }, { id: "action", label: "Next action" }];
const RECEIPT_COLUMNS = [{ id: "receipt", label: "Receipt", isRowHeader: true }, { id: "supplier", label: "Supplier" }, { id: "lines", label: "Cost coverage" }, { id: "cost", label: "Known cost" }, { id: "source", label: "Source" }];
const TASK_COLUMNS = [{ id: "task", label: "Open work", isRowHeader: true }, { id: "owner", label: "Owner" }, { id: "status", label: "Status" }, { id: "action", label: "Next action" }];
const NO_PO_COLUMNS = [{ id: "period", label: "Month", isRowHeader: true }, { id: "currency", label: "Currency" }, { id: "received", label: "No-PO receipts" }, { id: "approved", label: "Approved" }, { id: "pending", label: "Awaiting approval" }, { id: "amount", label: "Known amount" }];
const NO_PO_DETAIL_COLUMNS = [{ id: "date", label: "Date", isRowHeader: true }, { id: "vendor", label: "Vendor" }, { id: "amount", label: "Amount" }, { id: "receiver", label: "Receiver" }, { id: "reason", label: "Reason" }, { id: "decision", label: "Decision" }];
const CUSTODY_STATUS = { awaiting_handoff: "Awaiting handoff", received_pending_review: "Pending inspection", hold: "On hold", repair: "In repair", repair_complete_pending_review: "Repair ready for review", quarantine: "Quarantined", core_pending_return: "Core return pending", scrap_pending_approval: "Scrap approval pending", released: "Released to stock", core_returned: "Core returned", scrapped: "Scrapped" };
const SUMMARY_LABELS = [["awaiting_handoff", "Awaiting handoff"], ["pending_inspection", "Pending inspection"], ["hold", "On hold"], ["repair", "In repair"], ["quarantine", "Quarantined"], ["core_pending", "Core pending"], ["scrap_pending", "Scrap pending"], ["released_exact_position", "Released to a position"], ["core_returned", "Core returned"], ["scrapped", "Scrapped"]];

const list = (value) => Array.isArray(value) ? value : [];
function known(value) { return value === null || value === undefined || String(value).trim() === "" ? "Unknown" : String(value); }
function count(value) { return Number.isFinite(Number(value)) && value !== "" && value !== null ? Number(value).toLocaleString(undefined, { maximumFractionDigits: 3 }) : "Unknown"; }
function friendlyToken(value) { const text = known(value); return text === "Unknown" ? text : text.replaceAll("_", " ").replace(/^./, (letter) => letter.toUpperCase()); }
function reconciliationState(item) { if (item.quantity_delta === null || item.quantity_delta === undefined || item.reserved_delta === null || item.reserved_delta === undefined) return "Unknown"; return Number(item.quantity_delta) === 0 && Number(item.reserved_delta) === 0 ? "Matched" : "Mismatch"; }
function custodyAge(value) { const seconds = Number(value); if (!Number.isFinite(seconds) || seconds < 0) return "Unknown"; const days = Math.floor(seconds / 86400); if (days) return `${days}d`; const hours = Math.floor(seconds / 3600); if (hours) return `${hours}h`; return `${Math.floor(seconds / 60)}m`; }
function custodyPlace(item) { if (item.position_path) return item.position_path; if (item.position_code || item.position_name) return [item.position_code, item.position_name].filter(Boolean).join(" · "); if (item.custody_bin_location) return `${known(item.location_name)} · ${item.custody_bin_location}`; const external = item.external_reference || item.custody_external_reference; if (external) return external; if (["core_returned", "scrapped"].includes(item.status)) return friendlyToken(item.final_route); return known(item.location_name); }
function inventoryHref(section, fields = {}) { const params = new URLSearchParams({ view: "inventory", adminView: "inventory", inventorySection: section }); Object.entries(fields).forEach(([key, value]) => { if (value) params.set(key, value); }); return `?${params}`; }
function custodyHref(item, locationId) { return inventoryHref("tasks", { taskOwner: "custody", reuseCaseId: item.id, taskLocation: locationId }); }
function purchaseHref(item, locationId) { return inventoryHref("purchases", { purchaseOrderId: item.order_id || item.poId || item.purchaseOrderId || item.id, purchaseOrderNumber: item.number || item.order_number, taskLocation: locationId }); }
function invoiceHref(item) { const id = item.invoiceRunId || item.invoice_run_id || item.invoiceId; return id ? inventoryHref("inbound", { invoiceRun: id, receiptId: item.receiptId || item.receipt_id }) : ""; }
function receiptHref(item, locationId) { return inventoryHref("inbound", { receiptId: item.receiptId || item.receipt_id || item.id, taskLocation: locationId }); }
function deliveryHref(item, locationId) { return inventoryHref("inbound", { deliveryId: item.delivery_id || item.id, taskLocation: locationId }); }
function taskHref(item, locationId) { if (item.approval_request_id || item.approvalId || item.approval_id) return inventoryHref("inbound", { approvalId: item.approval_request_id || item.approvalId || item.approval_id, taskLocation: locationId }); if (item.sourceType === "removed_part_custody") return inventoryHref("tasks", { taskOwner: "custody", reuseCaseId: item.sourceId, taskLocation: locationId }); return inventoryHref("tasks", { taskOwner: item.taskOwner || item.ownerType || item.kind, taskId: item.task_id || item.sourceId || item.id, taskLocation: item.location_id || item.locationId || locationId }); }
function safeCsv(value) { const text = known(value); return `"${text.replace(/^[=+@-]/, "'$&").replaceAll('"', '""')}"`; }
function csvRows(data, locationId) {
  const rows = [["Section", "Reference", "Description", "Status", "Value 1", "Value 2", "Value 3", "Link"]];
  list(data.stock).forEach((entry) => rows.push(["Stock", entry.part_number, entry.description, entry.uom_code, entry.physical_on_hand, entry.quantity_reserved, entry.available, ""]));
  list(data.reconciliation?.rows).forEach((entry) => rows.push(["Reconciliation", entry.part_number, entry.description, reconciliationState(entry), entry.quantity_delta, entry.reserved_delta, entry.uom_code, ""]));
  list(data.openPurchaseOrders?.items).forEach((entry) => rows.push(["Purchase order", entry.number || entry.order_id, entry.supplier_name, entry.status, entry.remaining_quantity, entry.remaining_value, entry.currency, purchaseHref(entry, locationId)]));
  list(data.receiptBatches?.items).forEach((entry) => rows.push(["Receipt batch", entry.reference || entry.delivery_id, entry.supplier_name || entry.invoice_vendor, entry.status, entry.known_cost_lines, entry.unknown_cost_lines, entry.known_cost_total, deliveryHref(entry, locationId)]));
  list(data.tasks?.items).forEach((entry) => rows.push(["Open task", entry.task_id, entry.part_number, entry.status, entry.owner_name || entry.owner_id, entry.reason, entry.open_discrepancies, taskHref(entry, locationId)]));
  list(data.noPo?.items).forEach((entry) => rows.push(["No-PO receipt", entry.approval_request_id || entry.receipt_id, entry.vendor, entry.status, entry.amount, entry.purchaser_name, entry.reason, taskHref(entry, locationId)]));
  list(data.noPo?.trend).forEach((entry) => rows.push(["No-PO trend", entry.month, entry.currency, "", entry.count, entry.approved, entry.pending, entry.amount]));
  list(data.commitments).forEach((entry) => rows.push(["Commitment", entry.currency, "", "", entry.priced_commitment, entry.orders, entry.unpriced_lines, ""]));
  list(data.transfers || data.transit).forEach((entry) => rows.push(["Transfer", entry.part_number, entry.destination, entry.outcome || entry.transfer_state, entry.in_transit_quantity ?? entry.quantity, entry.received_quantity, entry.open_discrepancies, ""]));
  list(data.custody?.items).forEach((entry) => rows.push(["Custody", entry.part_number, entry.serial_number, entry.status, entry.location_name, entry.invoice_number || entry.invoice_file_name, entry.receipt_id, ""]));
  list(data.bills).forEach((entry) => rows.push(["Supplier bill", entry.currency, "", "", entry.outstanding, entry.overdue, "", ""]));
  rows.push(["Cost completeness", "Receipt lines", "", "", data.costCoverage?.receipt_lines, data.costCoverage?.unknown_cost_lines, "", ""]);
  return rows;
}

export function InventoryReports({ locations }) {
  const [locationId, setLocationId] = useState(locations[0]?.id || "");
  const [data, setData] = useState(null);
  const [error, setError] = useState("");
  const [page, setPage] = useState(1);
  const [refresh, setRefresh] = useState(0);
  useEffect(() => { if (!locationId && locations.length) setLocationId(locations[0].id); }, [locations, locationId]);
  useEffect(() => { if (!locationId) return undefined; let active = true; setError(""); setData(null); api(`/api/office/inventory/reports?${new URLSearchParams({ locationId, page: String(page) })}`).then((result) => { if (active) setData(result); }).catch((nextError) => { if (active) setError(nextError.message || "Could not load inventory reports."); }); return () => { active = false; }; }, [locationId, page, refresh]);
  function download() { if (!data) return; const url = URL.createObjectURL(new Blob([csvRows(data, locationId).map((row) => row.map(safeCsv).join(",")).join("\r\n")], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `inventory-report-page-${page}.csv`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  const reconciliation = list(data?.reconciliation?.rows), purchaseOrders = list(data?.openPurchaseOrders?.items), receipts = list(data?.receiptBatches?.items), tasks = list(data?.tasks?.items), taskSummary = list(data?.tasks?.summary), noPoItems = list(data?.noPo?.items), noPoTrend = list(data?.noPo?.trend);
  const taskTotal = taskSummary.reduce((total, item) => total + Number(item.count || 0), 0), exceptionTotal = taskSummary.reduce((total, item) => total + Number(item.open_exception_count || 0), 0), noPoPending = noPoItems.filter((item) => item.status === "pending").length;
  return <section className="inventory-workflows">
    <div className="inventory-workflow-toolbar"><label>Location<Dropdown value={locationId} onChange={(event) => { setLocationId(event.target.value); setPage(1); }}>{locations.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</Dropdown></label><Button onClick={() => setRefresh((value) => value + 1)}>Refresh</Button><Button disabled={!data} onClick={download}>Export report</Button></div>
    {error ? <p role="alert">{error}</p> : null}
    {data ? <>
      <h3>Stock and usage</h3><p>Tracked stock includes goods held for inspection or with a repair provider. In-transit stock is shown separately. Usage covers recorded issues in the last 30 days.</p>
      <OperationalDataTable ariaLabel="Stock and usage" columns={STOCK_COLUMNS} className="inventory-report-table">{list(data.stock).map((stock) => <OperationalDataRow id={stock.id} key={stock.id}><OperationalDataCell label="Part"><strong>{known(stock.part_number)}</strong><small>{known(stock.description)}</small></OperationalDataCell><OperationalDataCell label="Unit">{known(stock.uom_code)}</OperationalDataCell><OperationalDataCell label="Tracked total">{count(stock.physical_on_hand)}</OperationalDataCell><OperationalDataCell label="Held / repair">{count(stock.held_quantity)}</OperationalDataCell><OperationalDataCell label="Reserved">{count(stock.quantity_reserved)}</OperationalDataCell><OperationalDataCell label="Available">{count(stock.available)}</OperationalDataCell><OperationalDataCell label="Used (30 days)">{count(stock.used_last_30_days)}</OperationalDataCell></OperationalDataRow>)}</OperationalDataTable>
      {page > 1 || data.hasMore ? <div className="inventory-request-actions"><Button disabled={page === 1} onClick={() => setPage((value) => value - 1)}>Previous</Button> Page {page} <Button disabled={!data.hasMore} onClick={() => setPage((value) => value + 1)}>Next</Button></div> : null}
      <details open><summary>Reconciliation</summary><p>Position totals are compared with stock records. Differences require review before any correction.</p>{reconciliation.length ? <OperationalDataTable ariaLabel="Reconciliation status" columns={RECONCILIATION_COLUMNS} className="inventory-report-table">{reconciliation.map((item, index) => { const state = reconciliationState(item); return <OperationalDataRow id={item.inventory_item_id || `reconciliation-${index}`} key={item.inventory_item_id || index}><OperationalDataCell label="Status">{state}</OperationalDataCell><OperationalDataCell label="Scope"><strong>{known(item.part_number)}</strong><small>{known(item.description)} · {known(item.uom_code)}</small></OperationalDataCell><OperationalDataCell label="Difference">Stock {count(item.quantity_delta)} · Reserved {count(item.reserved_delta)}</OperationalDataCell><OperationalDataCell label="Next action">{state === "Mismatch" ? "Review physical count" : state === "Matched" ? "None" : "Review missing position evidence"}</OperationalDataCell></OperationalDataRow>; })}</OperationalDataTable> : <p>No stock records reported.</p>}</details>
      <details><summary>Latest receipts and costs</summary>{receipts.length ? <OperationalDataTable ariaLabel="Latest receipt cost evidence" columns={RECEIPT_COLUMNS} className="inventory-report-table">{receipts.map((receipt, index) => <OperationalDataRow id={receipt.delivery_id || `receipt-${index}`} key={receipt.delivery_id || index}><OperationalDataCell label="Receipt"><a href={deliveryHref(receipt, locationId)}>{known(receipt.reference || receipt.delivery_id)}</a><small>{known(receipt.received_at)}</small></OperationalDataCell><OperationalDataCell label="Supplier">{known(receipt.supplier_name || receipt.invoice_vendor)}</OperationalDataCell><OperationalDataCell label="Cost coverage">{count(receipt.known_cost_lines)} known · {count(receipt.unknown_cost_lines)} unknown</OperationalDataCell><OperationalDataCell label="Known cost">{receipt.known_cost_total === null ? "Unknown" : `${known(receipt.currency)} ${receipt.known_cost_total}`}</OperationalDataCell><OperationalDataCell label="Source">{invoiceHref(receipt) ? <a href={invoiceHref(receipt)}>Invoice {known(receipt.invoice_number)}</a> : receipt.order_id ? <a href={purchaseHref({ order_id: receipt.order_id }, locationId)}>PO {known(receipt.order_number)}</a> : "Unknown"}</OperationalDataCell></OperationalDataRow>)}</OperationalDataTable> : <p>No receipt batches reported. Cost is Unknown.</p>}</details>
      <details><summary>Open tasks and exceptions</summary><p>{count(taskTotal)} open · {count(exceptionTotal)} exceptions</p>{tasks.length ? <OperationalDataTable ariaLabel="Open inventory tasks and exceptions" columns={TASK_COLUMNS} className="inventory-report-table">{tasks.map((task, index) => <OperationalDataRow id={task.task_id || `task-${index}`} key={task.task_id || index}><OperationalDataCell label="Open work"><a href={taskHref(task, locationId)}>{known(task.part_number)}</a><small>{friendlyToken(task.kind)}</small></OperationalDataCell><OperationalDataCell label="Owner">{known(task.owner_name || task.owner_id)}</OperationalDataCell><OperationalDataCell label="Status">{friendlyToken(task.status)}</OperationalDataCell><OperationalDataCell label="Next action">{known(task.reason)}</OperationalDataCell></OperationalDataRow>)}</OperationalDataTable> : <p>No open tasks or exceptions reported.</p>}</details>
      <details><summary>No-PO compliance</summary><p>{count(noPoItems.length)} recorded · {count(noPoPending)} awaiting approval</p>{noPoItems.length ? <OperationalDataTable ariaLabel="No-PO receipt evidence" columns={NO_PO_DETAIL_COLUMNS} className="inventory-report-table">{noPoItems.map((item) => <OperationalDataRow id={item.approval_request_id || item.receipt_id} key={item.approval_request_id || item.receipt_id}><OperationalDataCell label="Date">{item.approval_request_id ? <a href={taskHref(item, locationId)}>{known(item.created_at)}</a> : <a href={receiptHref(item, locationId)}>{known(item.created_at)}</a>}<small>{known(item.location_name)}</small></OperationalDataCell><OperationalDataCell label="Vendor">{known(item.vendor)}</OperationalDataCell><OperationalDataCell label="Amount">{item.amount === null || !item.currency ? "Unknown" : `${item.currency} ${item.amount}`}</OperationalDataCell><OperationalDataCell label="Receiver">{known(item.purchaser_name)}</OperationalDataCell><OperationalDataCell label="Reason">{known(item.reason)}</OperationalDataCell><OperationalDataCell label="Decision">{friendlyToken(item.status)} · {known(item.approver_name)}</OperationalDataCell></OperationalDataRow>)}</OperationalDataTable> : <p>No No-PO receipts reported.</p>}{noPoTrend.length ? <OperationalDataTable ariaLabel="No-PO compliance trend" columns={NO_PO_COLUMNS} className="inventory-report-table">{noPoTrend.map((period, index) => <OperationalDataRow id={`no-po-${period.month || index}-${period.currency || "unknown"}`} key={`${period.month || index}:${period.currency || "unknown"}`}><OperationalDataCell label="Month">{known(period.month)}</OperationalDataCell><OperationalDataCell label="Currency">{known(period.currency)}</OperationalDataCell><OperationalDataCell label="No-PO receipts">{count(period.count)}</OperationalDataCell><OperationalDataCell label="Approved">{count(period.approved)}</OperationalDataCell><OperationalDataCell label="Awaiting approval">{count(period.pending)}</OperationalDataCell><OperationalDataCell label="Known amount">{period.amount === null || !period.currency ? "Unknown" : `${period.currency} ${count(period.amount)}`}</OperationalDataCell></OperationalDataRow>)}</OperationalDataTable> : <p>No No-PO trend reported.</p>}</details>
      <h3>Open purchasing commitments</h3>{list(data.commitments).length ? <OperationalDataTable ariaLabel="Open purchasing commitments" columns={COMMITMENT_COLUMNS} className="inventory-report-table">{list(data.commitments).map((commitment, index) => <OperationalDataRow id={commitment.currency || index} key={commitment.currency || index}><OperationalDataCell label="Currency">{known(commitment.currency)}</OperationalDataCell><OperationalDataCell label="Priced commitment">{known(commitment.priced_commitment)}</OperationalDataCell><OperationalDataCell label="Orders">{purchaseOrders.length ? <a href={purchaseHref(purchaseOrders[0], locationId)}>{count(commitment.orders)}</a> : count(commitment.orders)}</OperationalDataCell><OperationalDataCell label="Unpriced lines">{count(commitment.unpriced_lines)}</OperationalDataCell></OperationalDataRow>)}</OperationalDataTable> : <p>No approved outstanding orders.</p>}{purchaseOrders.length ? <details><summary>Purchase-order evidence</summary><ul>{purchaseOrders.map((order, index) => <li key={order.id || index}><a href={purchaseHref(order, locationId)}>{known(order.number || order.poNumber || order.id)}</a> · {known(order.status)} · {known(order.supplier || order.supplierName)}</li>)}</ul></details> : null}
      <h3>Transfers</h3><p>Open transfers and the last 90 days of completed activity. Lost, damaged, returned, and unresolved quantities remain separate.</p>{list(data.transfers || data.transit).length ? <OperationalDataTable ariaLabel="Transfer activity" columns={TRANSIT_COLUMNS} className="inventory-report-table">{list(data.transfers || data.transit).map((transfer, index) => <OperationalDataRow id={transfer.id || `${transfer.part_number}:${index}`} key={transfer.id || `${transfer.part_number}:${index}`}><OperationalDataCell label="Part"><a href={taskHref({ ...transfer, taskOwner: "transfer", sourceId: transfer.id }, locationId)}>{known(transfer.part_number)}</a></OperationalDataCell><OperationalDataCell label="Status">{friendlyToken(transfer.outcome || transfer.transfer_state || "in_transit")}</OperationalDataCell><OperationalDataCell label="In transit">{count(transfer.in_transit_quantity ?? transfer.quantity)} {known(transfer.uom_code)}</OperationalDataCell><OperationalDataCell label="Received">{count(transfer.received_quantity)} {known(transfer.uom_code)}</OperationalDataCell><OperationalDataCell label="Exceptions">Damaged {count(transfer.damaged_quantity)} · Lost {count(transfer.lost_quantity)} · Returned {count(transfer.returned_quantity)}{Number(transfer.open_discrepancies || 0) ? ` · ${transfer.open_discrepancies} open` : ""}</OperationalDataCell><OperationalDataCell label="Route">{known(transfer.source || data.locationName)}</OperationalDataCell><OperationalDataCell label="Destination">{known(transfer.destination)}</OperationalDataCell><OperationalDataCell label="Holder">{known(transfer.holder)}</OperationalDataCell></OperationalDataRow>)}</OperationalDataTable> : <p>No transfer activity.</p>}
      <h3>Removed parts / custody</h3><p>Current handoffs, inspections, repairs, dispositions, and recent completed outcomes for this location.</p><ul aria-label="Custody totals">{SUMMARY_LABELS.map(([key, label]) => <li key={key}><strong>{count(data.custody?.summary?.[key])}</strong> {label}</li>)}</ul>{list(data.custody?.items).length ? <OperationalDataTable ariaLabel="Removed parts and custody" columns={CUSTODY_COLUMNS} className="inventory-report-table">{data.custody.items.map((item) => <OperationalDataRow id={item.id} key={item.id}><OperationalDataCell label="Status"><strong>{CUSTODY_STATUS[item.status] || "Unknown"}</strong><a href={custodyHref(item, locationId)}>Open custody record</a></OperationalDataCell><OperationalDataCell label="Age">{custodyAge(item.age_seconds)}</OperationalDataCell><OperationalDataCell label="Part / serial"><strong>{known(item.part_number)}</strong><small>{known(item.description)} · Serial {known(item.serial_number)}</small></OperationalDataCell><OperationalDataCell label="Unit / workorder"><span>Unit {known(item.unit_no)}</span><small>{item.original_workorder_id ? <a href={workorderDetailSearch(item.original_workorder_id)}>{known(item.original_workorder_serial)}</a> : "Workorder Unknown"}{item.removal_workorder_id && item.removal_workorder_id !== item.original_workorder_id ? <> · <a href={workorderDetailSearch(item.removal_workorder_id)}>{known(item.removal_workorder_serial)}</a></> : null}</small></OperationalDataCell><OperationalDataCell label="Location / disposition">{custodyPlace(item)}</OperationalDataCell><OperationalDataCell label="Purchase record"><span>{invoiceHref(item) ? <a href={invoiceHref(item)}>Invoice {known(item.invoice_number || item.invoice_file_name)}</a> : `Invoice ${known(item.invoice_number || item.invoice_file_name)}`}</span><small>Receipt {item.receipt_id ? <a href={receiptHref(item, locationId)}>{item.receipt_id.slice(0, 8)}</a> : "Unknown"} · Cost {item.unit_cost === null || item.unit_cost === undefined ? "Unknown" : `${known(item.currency)} ${item.unit_cost}`} · Source {friendlyToken(item.cost_source)}</small></OperationalDataCell></OperationalDataRow>)}</OperationalDataTable> : <p>No removed parts or custody history.</p>}{data.custody?.hasMore ? <p role="status">Showing the latest {data.custody.limit} custody records.</p> : null}
      <h3>Supplier money outstanding</h3>{list(data.bills).length ? <OperationalDataTable ariaLabel="Supplier money outstanding" columns={BILL_COLUMNS} className="inventory-report-table">{data.bills.map((bill, index) => <OperationalDataRow id={bill.currency || index} key={bill.currency || index}><OperationalDataCell label="Currency">{known(bill.currency)}</OperationalDataCell><OperationalDataCell label="Outstanding">{known(bill.outstanding)}</OperationalDataCell><OperationalDataCell label="Overdue">{known(bill.overdue)}</OperationalDataCell></OperationalDataRow>)}</OperationalDataTable> : <p>No supplier bills recorded.</p>}
      <h3>Cost completeness</h3><p>{count(data.costCoverage?.unknown_cost_lines)} of {count(data.costCoverage?.receipt_lines)} receipt lines have unknown costs. A stock valuation is not published until the valuation policy and currency records are established.</p>
    </> : !error ? <p role="status">Loading reports...</p> : null}
  </section>;
}
