import './inventory-tables.css';
import { sendInventoryCommand,inventoryCommandCanBeEdited } from './inventory-command.js';
import { useEffect,useState } from 'react';
import { api } from '../../lib/api.js';
import { Button } from '../../components/ui/Button.jsx';
import { Checkbox } from '../../components/ui/Checkbox.jsx';
import { Dropdown } from '../../components/forms/Dropdown.jsx';
import { PartCatalogCombobox } from '../../components/workorders/part-requests/PartCatalogCombobox.jsx';
import { SecondaryDetailPanel,SecondaryDetailSection } from '../../components/ui/SecondaryDetailPanel.jsx';
import { OperationalDataCell,OperationalDataRow,OperationalDataTable } from '../../components/ui/OperationalDataTable.jsx';
import { StoragePositionPicker } from './StoragePositionPicker.jsx';
import { transferAllocationMatchesQuantity,transferDispatchPayload,transferDiscrepancyPayload,transferEventLabel,transferNextStep,transferReceiptPayload,transferReturnPayload,transferStatus } from './inventory-transfer-model.js';
import './inventory-workflows.css';
const labels={damage:'Damaged stock',transfer:'Transfers',count:'Cycle counts'};
const taskColumns=kind=>[
 {id:'part',label:kind==='damage'?'Part / PO':'Part',isRowHeader:true},
 {id:'quantity',label:'Quantity'},
 {id:'status',label:'Status'},
 {id:'holder',label:'Holder'},
 ...(kind==='transfer'?[{id:'destination',label:'Destination'}]:[]),
];
const serials=value=>value.split(/\r?\n/).map(s=>s.trim()).filter(Boolean);
export function InventoryStockTasks({locations,actorId,kind,initialPart=null,initialLocationId="",initialTaskId="",onOpenLocations,onImportCount}){
 const [locationId,setLocationId]=useState(initialLocationId||locations[0]?.id||''),[data,setData]=useState(null),[refresh,setRefresh]=useState(0),[page,setPage]=useState(1);
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState(null),[creating,setCreating]=useState(!!initialPart),[snapshot,setSnapshot]=useState(null);
 const [query,setQuery]=useState(initialPart?.partNumber||''),[part,setPart]=useState(initialPart),[quantity,setQuantity]=useState(initialPart?.damageSerialNumber?'1':''),[identities,setIdentities]=useState(initialPart?.damageSerialNumber||''),[reason,setReason]=useState(''),[holder,setHolder]=useState(''),[destinationId,setDestinationId]=useState('');
 const [sourceAllocations,setSourceAllocations]=useState([]),[blindReceiving,setBlindReceiving]=useState(false),[disposition,setDisposition]=useState('good'),[discrepancyType,setDiscrepancyType]=useState('short'),[resolutionType,setResolutionType]=useState('lost_in_transit');
 const [targetPositionId,setTargetPositionId]=useState(''),[positions,setPositions]=useState([]),[positionLoading,setPositionLoading]=useState(false),[positionError,setPositionError]=useState(''),[positionRefresh,setPositionRefresh]=useState(0);
 const [routedPart,setRoutedPart]=useState(initialPart?.damageSerialNumber?initialPart:null);
 const [initialTaskPending,setInitialTaskPending]=useState(Boolean(initialTaskId));
 const [initialTaskError,setInitialTaskError]=useState(''),[initialTaskRetry,setInitialTaskRetry]=useState(0);
 const key=`inventory-task-command:${actorId}:${locationId}`,[pending,setPending]=useState(null);
 function clearNewTask(){setRoutedPart(null);setPart(null);setQuery('');setSnapshot(null);setQuantity('');setIdentities('');setReason('');setHolder('');setDestinationId('');setSourceAllocations([]);setBlindReceiving(false);setDisposition('good');setDiscrepancyType('short');setResolutionType('lost_in_transit');}
 function changeLocation(nextLocationId){if(nextLocationId===locationId)return;setLocationId(nextLocationId);setData(null);setError('');setSelected(null);setCreating(false);clearNewTask();}
 useEffect(()=>{if(!locationId&&locations.length)setLocationId(locations[0].id);},[locations,locationId]);
 useEffect(()=>{setPage(1);setSelected(null);try{setPending(JSON.parse(localStorage.getItem(key)));}catch{setPending(null);}},[key]);
 useEffect(()=>{if(!locationId)return;let active=true;api(`/api/office/inventory/stock-tasks?${new URLSearchParams({locationId,kind,page:String(page)})}`).then(d=>{if(active){setData(d);setError('');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[locationId,kind,page,refresh]);
 useEffect(()=>{setInitialTaskPending(Boolean(initialTaskId));setInitialTaskError('');},[initialTaskId]);
 useEffect(()=>{if(!initialTaskPending||!initialTaskId||!locationId)return undefined;let active=true;setInitialTaskError('');api(`/api/office/inventory/stock-tasks/${encodeURIComponent(initialTaskId)}?${new URLSearchParams({locationId,kind})}`).then(result=>{if(active){setSelected(result.task);setCreating(false);setInitialTaskPending(false);}}).catch(next=>{if(active){setInitialTaskError(next.message||'This stock task could not be opened.');setInitialTaskPending(false);}});return()=>{active=false;};},[initialTaskId,initialTaskPending,initialTaskRetry,kind,locationId]);
 useEffect(()=>{setSnapshot(null);if(!part||!locationId)return;let active=true;api(`/api/office/inventory/stock-tasks/snapshot?${new URLSearchParams({locationId,catalogPartId:part.id||part.catalogPartId})}`).then(s=>{if(active)setSnapshot(s);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[part,locationId,refresh]);
 const exactDestinationPurpose=selected?.kind==='transfer'&&selected.status==='in_transit'&&[selected.location_id,selected.destination_id].includes(locationId)?'transfer_receive':selected?.kind==='damage'&&['inspection','repair'].includes(selected.status)&&selected.location_id===locationId?'damage_release':'';
 useEffect(()=>{setTargetPositionId('');setPositions([]);setPositionError('');if(!exactDestinationPurpose||!locationId)return undefined;let active=true;setPositionLoading(true);api(`/api/office/inventory/locations/${encodeURIComponent(locationId)}/positions`).then(result=>{if(active)setPositions(result.positions||result.items||[]);}).catch(next=>{if(active)setPositionError(next.message||'Storage destinations could not be loaded.');}).finally(()=>{if(active)setPositionLoading(false);});return()=>{active=false;};},[exactDestinationPurpose,locationId,selected?.id,positionRefresh]);
 async function command(body){
  if(busy)return;setBusy(true);setError('');const request=pending||{...body,locationId,idempotencyKey:crypto.randomUUID()};
  try{
   localStorage.setItem(key,JSON.stringify(request));setPending(request);
   const result=await sendInventoryCommand({request,recover:!!pending,url:'/api/office/inventory/stock-tasks'});
   localStorage.removeItem(key);setPending(null);setSelected(result.task);setCreating(false);setRefresh(x=>x+1);setReason('');setHolder('');setIdentities('');setQuantity('');setTargetPositionId('');setDisposition('good');
  }catch(e){setError(e.message);if(inventoryCommandCanBeEdited(e)){localStorage.removeItem(key);setPending(null);}}finally{setBusy(false);}
 }
 useEffect(()=>{if(kind!=='damage')return;const refreshDamage=()=>setRefresh(value=>value+1);const timer=setInterval(refreshDamage,15000);window.addEventListener('focus',refreshDamage);return()=>{clearInterval(timer);window.removeEventListener('focus',refreshDamage);};},[kind]);
 const action=(name)=>{
  const requiresTarget=['receive_transfer','receive_transfer_return','release'].includes(name)||name==='report_transfer_discrepancy'&&discrepancyType==='extra';
  if(requiresTarget&&!targetPositionId){setError('Choose the exact shelf or bin before confirming this stock movement.');return;}
  if(name==='receive_transfer')return command(transferReceiptPayload({task:selected,locationId,quantity,reason,holder,serialNumbers:serials(identities),targetPositionId,disposition}));
  if(name==='report_transfer_discrepancy')return command(transferDiscrepancyPayload({task:selected,locationId,discrepancyType,quantity,reason,holder,serialNumbers:serials(identities),targetPositionId}));
  if(['request_transfer_return','receive_transfer_return'].includes(name))return command(transferReturnPayload({task:selected,locationId,reason,holder,action:name,...(name==='receive_transfer_return'?{quantity,serialNumbers:serials(identities),targetPositionId}:{})}));
  command({action:name,taskId:selected.id,expectedVersion:selected.version,reason,holder,serialNumbers:serials(identities),...(['recount'].includes(name)?{quantity:Number(quantity)}:{}),...(requiresTarget?{targetPositionId}:{})});
 };
 const resolveTransferDiscrepancy=(discrepancyId,exception)=>{const type=exception.kind||exception.discrepancy_type||exception.type,resolution=type==='extra'?'extra_returned':resolutionType;return command({action:'resolve_transfer_discrepancy',taskId:selected.id,locationId,expectedVersion:selected.version,discrepancyId,resolutionType:resolution,resolutionReference:holder,...(resolution==='lost_in_transit'?{quantity:Number(quantity),serialNumbers:serials(identities)}:{serialNumbers:[]}),reason,holder});};
 if(kind==='count'&&!initialTaskId)return <section className="inventory-workflows"><div className="inventory-workflow-toolbar"><label>Location<Dropdown value={locationId} onChange={e=>setLocationId(e.target.value)}>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</Dropdown></label></div><div className="inventory-workflow-form"><h3>Physical counts</h3><p>Choose a shop to count stock in its storage locations. Import starting inventory only when setting up or migrating a shop.</p><div className="inventory-request-actions"><Button type="button" variant="primary" disabled={!locationId||!onOpenLocations} onClick={()=>onOpenLocations?.(locationId)}>Open stock by location</Button><Button id="inventory-import-count-action" type="button" disabled={!onImportCount} onClick={()=>onImportCount?.()}>Import starting inventory</Button></div></div></section>;
 return <section className="inventory-workflows">
  <div className="inventory-workflow-toolbar"><label>Location<Dropdown value={locationId} disabled={busy||!!pending} onChange={e=>changeLocation(e.target.value)}>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</Dropdown></label><Button onClick={()=>setRefresh(x=>x+1)}>Refresh</Button><Button variant="primary" disabled={!!pending} onClick={()=>{clearNewTask();setSelected(null);setCreating(true);}}>{kind==='damage'?'Mark stock damaged':kind==='transfer'?'Dispatch transfer':'Record count'}</Button></div>
  {initialTaskError?<p role="alert" className="ops-error">{initialTaskError} <Button type="button" onClick={()=>{setInitialTaskPending(true);setInitialTaskRetry(value=>value+1);}}>Try again</Button></p>:null}
  {error?<p role="alert" className="ops-error">{error}</p>:null}{pending?<p role="status">A saved action needs confirmation. <Button disabled={busy} onClick={()=>command(pending)}>Check saved action</Button></p>:null}
  {creating&&kind==='transfer'?<TransferDispatchForm locations={locations} locationId={locationId} part={part} query={query} setQuery={setQuery} setPart={setPart} snapshot={snapshot} quantity={quantity} setQuantity={setQuantity} identities={identities} setIdentities={setIdentities} destinationId={destinationId} setDestinationId={setDestinationId} holder={holder} setHolder={setHolder} reason={reason} setReason={setReason} sourceAllocations={sourceAllocations} setSourceAllocations={setSourceAllocations} blindReceiving={blindReceiving} setBlindReceiving={setBlindReceiving} busy={busy||!!pending} onClose={()=>setCreating(false)} onSubmit={()=>command(transferDispatchPayload({locationId,catalogPartId:part.id||part.catalogPartId,quantity,expectedBalanceRevision:snapshot.revision,destinationId,reason,holder,serialNumbers:serials(identities),sourceAllocations,blindReceiving}))}/>:null}
  {creating&&kind!=='transfer'?<form className="inventory-workflow-form" onSubmit={e=>{e.preventDefault();command({action:kind,catalogPartId:part.id||part.catalogPartId,quantity:Number(quantity),expectedBalanceRevision:snapshot.revision,reason,holder,serialNumbers:serials(identities)});}}>
   <h3>{routedPart?'Block damaged unit':labels[kind]}</h3>{routedPart?<p><strong>{routedPart.partNumber}</strong> - {routedPart.damageSerialNumber}. Only this unit will be held for inspection.</p>:null}{!routedPart?<PartCatalogCombobox locationId={locationId} purpose="master_match" catalogEndpoint="/api/office/inventory/catalog" value={query} onChange={value=>{setQuery(value);setPart(null);}} onSelect={value=>{setPart(value);setQuery(value.partNumber);}} />:null}
   {snapshot?<p>Usable stock: {snapshot.quantity_on_hand} {snapshot.uom_code}; reserved: {snapshot.quantity_reserved}. Held and in-transit goods are excluded.</p>:<p>Choose a part to load its current stock.</p>}
   {kind==='count'&&snapshot?.tracking_mode==='serialized'?<p>Scan every usable unit physically present. Unseen identities become missing only after approval. Investigate unknown or held identities separately.</p>:null}
   <label>{kind==='count'?'Observed usable quantity':'Quantity'}<input readOnly={!!routedPart} required type="number" min={kind==='count'?'0':'0.001'} step="any" value={quantity} onChange={e=>setQuantity(e.target.value)} /></label>
   {snapshot?.tracking_mode==='serialized'?<label>Scan shop QR or enter exact serials, one per line<textarea readOnly={!!routedPart} required={kind!=='count'} value={identities} onChange={e=>{setIdentities(e.target.value);setQuantity(String(serials(e.target.value).length));}} /></label>:null}
   <label>{kind==='damage'?'Physical hold location':'Counted storage area'}<input required maxLength={240} value={holder} onChange={e=>setHolder(e.target.value)} /></label>
   <label>{kind==='count'?'Observation notes':'Reason / damage details'}<textarea required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} /></label>
   <p>{kind==='damage'?'Confirm these goods are physically separated from usable stock. Inspection or repair approval is required before release.':'Record only usable stock you physically counted. An administrator approves the variance; later stock activity requires a recount.'}</p>
   <div className="inventory-request-actions"><Button type="button" onClick={()=>setCreating(false)}>Close</Button><Button type="submit" variant="primary" disabled={busy||!!pending||!snapshot}>Confirm {kind==='damage'?'damage':'observation'}</Button></div>
  </form>:null}
  <h3>{labels[kind]}</h3>{!data?<p>Loading tasks...</p>:data.items.length?<OperationalDataTable ariaLabel={labels[kind]} columns={taskColumns(kind)} className="inventory-data-table inventory-stock-tasks-table">{data.items.map(t=><OperationalDataRow id={t.id} key={t.id}><OperationalDataCell label={kind==='damage'?'Part / PO':'Part'}><button type="button" className="inventory-table-link" onClick={()=>{setSelected(t);setCreating(false);setReason('');setHolder('');setIdentities('');setQuantity('');}}>{t.part_number}</button></OperationalDataCell><OperationalDataCell label="Quantity">{t.delivery_report?'See damage details':<>{t.quantity} {t.uom_code}</>}</OperationalDataCell><OperationalDataCell label="Status"><span className={`inventory-table-status is-${t.status}`}>{t.delivery_report?'Awaiting inventory entry':kind==='transfer'?transferStatus(t).label:t.status.replaceAll('_',' ')}</span></OperationalDataCell><OperationalDataCell label="Holder">{t.holder||'?'}</OperationalDataCell>{kind==='transfer'?<OperationalDataCell label="Destination">{t.destination_name||'?'}</OperationalDataCell>:null}</OperationalDataRow>)}</OperationalDataTable>:<p>{kind==='damage'?'No damaged stock reported at this location.':'No matching tasks at this shop.'}</p>}
  {page>1||data?.hasMore?<div className="inventory-request-actions"><Button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</Button> Page {page} <Button disabled={!data?.hasMore} onClick={()=>setPage(p=>p+1)}>Next</Button></div>:null}
  <SecondaryDetailPanel open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}} title={selected?`${selected.part_number} · ${labels[selected.kind]}`:'Task'}>
  {selected?.delivery_report?<SecondaryDetailSection title="Damage reported on delivery"><p>{selected.part_number} ? {selected.holder}</p><p className="purchase-delivery-notes">{selected.reason}</p><p>Delivery confirmed at {selected.location_name}. These goods have not all been added to inventory yet.</p><p>Open this PO in Purchases and choose Add to inventory. Add damaged quantities as ?Damaged / held for inspection? and undamaged quantities separately. The held stock will appear here for follow-up.</p></SecondaryDetailSection>:selected?.kind==='transfer'?<TransferDetail task={selected} locationId={locationId} positions={positions} targetPositionId={targetPositionId} setTargetPositionId={setTargetPositionId} positionLoading={positionLoading} positionError={positionError} retryPositions={()=>setPositionRefresh(value=>value+1)} busy={busy||!!pending} reason={reason} setReason={setReason} holder={holder} setHolder={setHolder} quantity={quantity} setQuantity={setQuantity} identities={identities} setIdentities={setIdentities} disposition={disposition} setDisposition={setDisposition} discrepancyType={discrepancyType} setDiscrepancyType={setDiscrepancyType} resolutionType={resolutionType} setResolutionType={setResolutionType} onAction={action} onResolveDiscrepancy={resolveTransferDiscrepancy}/>:selected?<div className="inventory-workflows"><SecondaryDetailSection title={selected.status.replaceAll('_',' ')}><p>{selected.reason}</p><p>{selected.quantity} {selected.uom_code} · {selected.location_name}{selected.destination_name?` · ${selected.destination_name}`:''}</p><p>Holder: {selected.holder}</p>{selected.kind==='count'?<p>Recorded balance: {selected.observed_balance} · Observed: {selected.quantity} · Variance: {Number(selected.quantity)-Number(selected.observed_balance)} {selected.uom_code}</p>:null}{selected.identity_observation?<p>Observed serials: {selected.identity_observation.observed.join(', ')||'None'}</p>:null}{selected.units.length?<ul>{selected.units.map(u=><li key={u.id}>{u.serial_number}{u.received_at?' · received':''}</li>)}</ul>:null}</SecondaryDetailSection>
   <SecondaryDetailSection title="Complete task"><label>Reason / inspection findings<textarea maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} /></label><label>{selected.kind==='transfer'?'Receiving note / handoff reference':selected.kind==='damage'?'Inspection / repair / disposal reference':'Count reference'}<input value={holder} maxLength={240} onChange={e=>setHolder(e.target.value)} /></label>{selected.tracking_mode==='serialized'?<label>Validate shop QR or exact serials, one per line<textarea value={identities} onChange={e=>{setIdentities(e.target.value);setQuantity(String(serials(e.target.value).length));}} /></label>:null}
    {['transfer','count'].includes(selected.kind)?<label>{selected.kind==='transfer'?'Quantity physically received':'Recounted usable quantity'}<input type="number" min="0" step="any" value={quantity} onChange={e=>setQuantity(e.target.value)} /></label>:null}
    {exactDestinationPurpose?<div className="inventory-task-exact-destination"><StoragePositionPicker positions={positions} value={targetPositionId} onChange={setTargetPositionId} disabled={busy||!!pending||positionLoading} required purpose={exactDestinationPurpose}/>{positionLoading?<p role="status">Loading eligible storage destinations…</p>:null}{positionError?<p role="alert">{positionError} <Button type="button" onClick={()=>setPositionRefresh(value=>value+1)} disabled={busy||!!pending}>Try again</Button></p>:null}</div>:null}
    <div className="inventory-workflow-toolbar">
     {selected.kind==='damage'&&['inspection','repair'].includes(selected.status)&&selected.location_id===locationId?<>{selected.status==='inspection'?<Button disabled={busy||!!pending||!reason.trim()||!holder.trim()} onClick={()=>action('repair')}>Send for repair</Button>:null}{data?.canApprove?<><Button disabled={busy||!!pending||!reason.trim()||!holder.trim()||!targetPositionId||positionLoading||!!positionError} onClick={()=>action('release')}>Approve inspected stock for use</Button><Button disabled={busy||!!pending||!reason.trim()||!holder.trim()} onClick={()=>action('scrap')}>Confirm scrap disposal</Button></>:<p>An administrator must approve release or disposal.</p>}</>:null}
     {selected.kind==='transfer'&&selected.status==='in_transit'&&selected.destination_id===locationId?<Button disabled={busy||!!pending||!reason.trim()||!holder.trim()||!quantity||!targetPositionId||positionLoading||!!positionError} onClick={()=>action('receive_transfer')}>Confirm transfer receipt</Button>:null}
     {selected.kind==='count'&&['awaiting_approval','recount'].includes(selected.status)?<>{selected.status==='awaiting_approval'&&data?.canApprove?<Button disabled={busy||!!pending||!reason.trim()} onClick={()=>action('approve_count')}>Approve count variance</Button>:null}<Button disabled={busy||!!pending||!reason.trim()||quantity===''} onClick={()=>action('recount')}>Save recount</Button><Button disabled={busy||!!pending||!reason.trim()} onClick={()=>action('cancel_count')}>Cancel count</Button></>:null}
    </div>{error?<p role="alert">{error}</p>:null}{pending?<Button disabled={busy} onClick={()=>command(pending)}>Check saved action</Button>:null}</SecondaryDetailSection><SecondaryDetailSection title="History"><ul>{selected.events.map((event,i)=><li key={i}>{event.action.replaceAll('_',' ')} · {new Date(event.created_at).toLocaleString()} · {event.details.reason}</li>)}</ul></SecondaryDetailSection></div>:null}
  </SecondaryDetailPanel>
 </section>;
}

function TransferDispatchForm({ locations,locationId,part,query,setQuery,setPart,snapshot,quantity,setQuantity,identities,setIdentities,destinationId,setDestinationId,holder,setHolder,reason,setReason,sourceAllocations,setSourceAllocations,blindReceiving,setBlindReceiving,busy,onClose,onSubmit }) {
 const serialized=snapshot?.tracking_mode==='serialized';
 const allocationByPosition=new Map(sourceAllocations.map(entry=>[entry.positionId,String(entry.quantity)]));
 const updateAllocation=(positionId,value)=>setSourceAllocations(current=>{
  const next=current.filter(entry=>entry.positionId!==positionId);
  return value===''||Number(value)<=0?next:[...next,{positionId,quantity:Number(value)}];
 });
 const allocated=sourceAllocations.reduce((total,entry)=>total+Number(entry.quantity||0),0);
 const validAllocation=serialized||transferAllocationMatchesQuantity(sourceAllocations,quantity,snapshot?.uom_code);
 return <form className="inventory-workflow-form inventory-transfer-dispatch" onSubmit={event=>{event.preventDefault();onSubmit();}}>
  <header><h3>Dispatch transfer</h3><p>Record where the goods left from and where they are going.</p></header>
  <PartCatalogCombobox locationId={locationId} purpose="master_match" catalogEndpoint="/api/office/inventory/catalog" value={query} onChange={value=>{setQuery(value);setPart(null);}} onSelect={value=>{setPart(value);setQuery(value.partNumber);}} />
  {!snapshot?<p role="status">Choose a part to load its available stock and source bins.</p>:<>
   <div className="inventory-transfer-summary"><span>Available</span><strong>{snapshot.quantity_on_hand} {snapshot.uom_code}</strong><span>Reserved</span><strong>{snapshot.quantity_reserved}</strong></div>
   <div className="inventory-transfer-grid"><label>Destination shop<Dropdown required value={destinationId} onChange={event=>setDestinationId(event.target.value)}><option value="">Choose destination</option>{locations.filter(location=>location.id!==locationId).map(location=><option key={location.id} value={location.id}>{location.name}</option>)}</Dropdown></label><label>Handoff reference<input required maxLength={240} value={holder} onChange={event=>setHolder(event.target.value)} placeholder="Driver, shipment, or handoff" /></label></div>
   <label>Quantity<input required type="number" min="0.001" step="any" value={quantity} onChange={event=>setQuantity(event.target.value)} /></label>
   {serialized?<label>Scan exact serials<textarea required value={identities} onChange={event=>{setIdentities(event.target.value);setQuantity(String(serials(event.target.value).length));}} placeholder="One serial or QR per line" /></label>:<section className="inventory-transfer-source"><div><h4>Pick from source bins</h4><p>Allocate the exact bins that physically supplied this transfer.</p></div>{(snapshot.positions||[]).length?(<div className="inventory-transfer-allocation-list">{snapshot.positions.map(position=><label key={position.positionId||position.id}><span>{position.code||position.name}<small>{position.availableQuantity} available</small></span><input aria-label={`Quantity from ${position.code||position.name}`} type="number" min="0" max={position.availableQuantity} step="any" value={allocationByPosition.get(position.positionId||position.id)||''} onChange={event=>updateAllocation(position.positionId||position.id,event.target.value)} /></label>)}</div>):<p role="alert">No pickable bins are available for this part. Reconcile its physical location before dispatching.</p>}<p className={validAllocation?'inventory-transfer-match':'inventory-transfer-warning'}>{allocated} of {quantity||0} allocated</p></section>}
   {serialized?<label className="inventory-transfer-check"><Checkbox checked={blindReceiving} onChange={event=>setBlindReceiving(event.target.checked)} />Hide expected serials from the receiver until they submit their scan</label>:null}
   <label>Transfer note<textarea required maxLength={500} value={reason} onChange={event=>setReason(event.target.value)} placeholder="Why this stock is moving" /></label>
  </>}
  <footer className="inventory-request-actions"><Button type="button" onClick={onClose}>Close</Button><Button type="submit" variant="primary" disabled={busy||!snapshot||!part||!destinationId||!holder.trim()||!reason.trim()||!quantity||!validAllocation}>Confirm dispatch</Button></footer>
 </form>;
}

function TransferDetail({ task,locationId,positions,targetPositionId,setTargetPositionId,positionLoading,positionError,retryPositions,busy,reason,setReason,holder,setHolder,quantity,setQuantity,identities,setIdentities,disposition,setDisposition,discrepancyType,setDiscrepancyType,resolutionType,setResolutionType,onAction,onResolveDiscrepancy }) {
 const atDestination=task.destination_id===locationId;
 const atSource=task.location_id===locationId;
 const blind=Boolean(task.blind_receiving&&atDestination&&task.status==='in_transit');
 const returning=task.transfer_state==='returning';
 const canReceive=atDestination&&task.status==='in_transit'&&!returning;
 const canReturn=atSource&&task.status==='in_transit'&&!returning;
 const canConfirmReturn=atSource&&returning;
 const status=transferStatus(task);
 const showPosition=canReceive&&disposition==='good'||canConfirmReturn;
 return <div className="inventory-workflows inventory-transfer-detail">
  <SecondaryDetailSection title={status.label}><div className="inventory-transfer-summary"><span>From</span><strong>{task.location_name}</strong><span>To</span><strong>{task.destination_name}</strong><span>Moving</span><strong>{task.quantity} {task.uom_code}</strong><span>Received</span><strong>{task.completed_quantity||0} {task.uom_code}</strong></div><p>{transferNextStep(task,locationId)}</p>{task.reason?<p className="inventory-transfer-note">{task.reason}</p>:null}{!blind&&task.units?.length?<ul className="inventory-transfer-units">{task.units.map(unit=><li key={unit.id}>{unit.serial_number}{unit.received_at?' · received':''}</li>)}</ul>:null}{blind?<p className="inventory-transfer-blind">Expected identities stay hidden until the receiving scan is submitted.</p>:null}</SecondaryDetailSection>
  {(canReceive||canConfirmReturn)?<SecondaryDetailSection title={canConfirmReturn?'Confirm physical return':'Receive goods'} description={canConfirmReturn?'Put returned goods back in their source bin.':'Record what actually arrived. Good goods enter stock only after exact put-away.'}><label>{canConfirmReturn?'Return note':'Receiving note'}<textarea maxLength={500} value={reason} onChange={event=>setReason(event.target.value)} /></label><label>Handoff reference<input maxLength={240} value={holder} onChange={event=>setHolder(event.target.value)} /></label><label>{canConfirmReturn?'Quantity returned':'Quantity received'}<input type="number" min="0" step="any" value={quantity} onChange={event=>setQuantity(event.target.value)} /></label>{task.tracking_mode==='serialized'?<label>{blind?'Scan received serials':'Validate received serials'}<textarea value={identities} onChange={event=>{setIdentities(event.target.value);setQuantity(String(serials(event.target.value).length));}} placeholder="One serial or QR per line" /></label>:null}{canReceive?<label>Condition<Dropdown value={disposition} onChange={event=>setDisposition(event.target.value)}><option value="good">Good — put away</option><option value="damaged">Damaged — hold for inspection</option></Dropdown></label>:null}{showPosition?<div className="inventory-task-exact-destination"><StoragePositionPicker positions={positions} value={targetPositionId} onChange={setTargetPositionId} disabled={busy||positionLoading} required purpose={canConfirmReturn?'transfer_return':'transfer_receive'}/>{positionLoading?<p role="status">Loading storage locations…</p>:null}{positionError?<p role="alert">{positionError} <Button type="button" onClick={retryPositions} disabled={busy}>Try again</Button></p>:null}</div>:null}{canReceive&&disposition==='damaged'?<TransferHoldPositionPicker positions={positions} value={targetPositionId} onChange={setTargetPositionId} disabled={busy||positionLoading}/>:null}<div className="inventory-request-actions"><Button type="button" variant="primary" disabled={busy||!reason.trim()||!holder.trim()||!quantity||!targetPositionId||positionLoading||!!positionError} onClick={()=>onAction(canConfirmReturn?'receive_transfer_return':'receive_transfer')}>{canConfirmReturn?'Confirm return':'Confirm receipt'}</Button></div></SecondaryDetailSection>:null}
  {(canReceive||canReturn)&&task.status==='in_transit'?<details className="inventory-transfer-exceptions"><summary>Report a discrepancy or return</summary><div><label>Exception<Dropdown value={discrepancyType} onChange={event=>setDiscrepancyType(event.target.value)}><option value="short">Short — less arrived</option><option value="extra">Extra — hold and investigate</option></Dropdown></label><label>Quantity<input type="number" min="0" step="any" value={quantity} onChange={event=>setQuantity(event.target.value)} /></label><label>What happened?<textarea maxLength={500} value={reason} onChange={event=>setReason(event.target.value)} /></label><label>Reference<input maxLength={240} value={holder} onChange={event=>setHolder(event.target.value)} /></label>{task.tracking_mode==='serialized'&&!blind?<label>Scanned serials<textarea value={identities} onChange={event=>setIdentities(event.target.value)} /></label>:null}{discrepancyType==='extra'?<TransferHoldPositionPicker positions={positions} value={targetPositionId} onChange={setTargetPositionId} disabled={busy||positionLoading}/>:null}<div className="inventory-request-actions"><Button type="button" disabled={busy||!reason.trim()||!holder.trim()||!quantity||(discrepancyType==='extra'&&!targetPositionId)} onClick={()=>onAction('report_transfer_discrepancy')}>Record {discrepancyType}</Button>{canReturn?<Button type="button" disabled={busy||!reason.trim()||!holder.trim()} onClick={()=>onAction('request_transfer_return')}>Start return to source</Button>:null}</div></div></details>:null}
  {(task.exceptions||[]).some(exception=>!exception.resolved_at)?<SecondaryDetailSection title="Resolve exceptions"><label>Resolution note<textarea required maxLength={500} value={reason} onChange={event=>setReason(event.target.value)} /></label><label>Resolution reference<input maxLength={240} value={holder} onChange={event=>setHolder(event.target.value)} /></label>{task.exceptions.filter(exception=>!exception.resolved_at).map(exception=>{const type=exception.kind||exception.discrepancy_type||exception.type,isLost=type==='short'&&resolutionType==='lost_in_transit',remaining=Number(exception.remaining_quantity??exception.quantity);return <div className="inventory-transfer-exception" key={exception.id}><span>{type} · {remaining} {task.uom_code} remaining{remaining!==Number(exception.quantity)?` of ${exception.quantity}`:''}</span>{type==='short'?<label>Resolution<Dropdown value={resolutionType} onChange={event=>setResolutionType(event.target.value)}><option value="received_or_returned">Goods received or returned</option><option value="lost_in_transit">Confirmed lost in transit</option></Dropdown></label>:<p>Confirm the unexpected goods were physically returned without adding them to stock.</p>}{isLost?<><label>Lost quantity<input type="number" min="0" max={remaining} step="any" placeholder={String(remaining)} value={quantity} onChange={event=>setQuantity(event.target.value)} /></label>{task.tracking_mode==='serialized'?<label>Lost serials<textarea value={identities} onChange={event=>setIdentities(event.target.value)} placeholder="One serial or QR per line" /></label>:null}</>:null}<Button type="button" disabled={busy||!reason.trim()||!holder.trim()||(isLost&&(!quantity||Number(quantity)>remaining||(task.tracking_mode==='serialized'&&!identities.trim())))} onClick={()=>onResolveDiscrepancy(exception.id,exception)}>Resolve</Button></div>;})}</SecondaryDetailSection>:null}
  <SecondaryDetailSection title="History"><ul>{(task.events||[]).map((event,index)=><li key={index}>{transferEventLabel(event)} · {new Date(event.created_at).toLocaleString()}</li>)}</ul></SecondaryDetailSection>
 </div>;
}

function TransferHoldPositionPicker({ positions = [],value,onChange,disabled }) {
 const holdPositions=positions.filter(position=>position.isActive!==false&&position.canStore===true&&position.isPickable===false&&!position.systemKey);
 return <label className="inventory-transfer-hold-picker">Put damaged goods in<Dropdown value={value} onChange={event=>onChange(event.target.value)} disabled={disabled} required><option value="">Choose a hold location</option>{holdPositions.map(position=><option key={position.id} value={position.id}>{position.path_label||position.pathLabel||position.code||position.name}</option>)}</Dropdown><small>Damaged goods stay out of usable stock and wait in a non-pickable hold location.</small></label>;
}
