import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

const component = new URL("./PartCommercialDetails.jsx", import.meta.url);
const styles = new URL("./part-commercial-details.css", import.meta.url);
test("commercial details keep batches visible and defer pricing and history", async () => { const source = await readFile(component, "utf8"); assert.doesNotMatch(source, /<h3>\{locationId \? "Prices" : "Company prices"\}<\/h3>/); assert.match(source, /Latest purchase cost/); assert.match(source, /Purchase history/); assert.match(source, /inventory-commercial-pricing-history/); assert.match(source, /Pricing &amp; history/); assert.doesNotMatch(source, /inventory-commercial-pricing-history" open/); assert.match(source, /sellingPolicySummary/); assert.match(source, /Same price for every batch/); assert.match(source, /Markup % on batch cost/); assert.match(source, /Add amount to batch cost/); assert.match(source, /<Dropdown/); assert.match(source, /<CurrencySelector/); assert.match(source, /type="submit" variant="primary"/); assert.doesNotMatch(source, /Internal price/); assert.match(source, /prices\.override\?\.history/); assert.match(source, /prices\.companyDefault\?\.history/); assert.match(source, /Company price defaults/); assert.match(source, /costs\.truncated/); });

test("commercial prices show read-only Odoo purchase-order evidence", async () => { const source = await readFile(component, "utf8"); assert.match(source, /details\.purchaseOrders/); assert.match(source, /Latest Odoo PO price/); assert.match(source, />Odoo purchase orders</); assert.match(source, /entry\.orderNumber/); assert.match(source, /entry\.vendorName/); assert.match(source, /entry\.receivedQuantity/); });

test("selling policy previews current priced batches including audited corrections", async () => { const source = await readFile(component, "utf8"); assert.match(source, /const preview = valid \?/); assert.match(source, /entry\.status === "known" \|\| \(entry\.unitCost !== null && entry\.currency\)/); assert.match(source, /observations=\{availableBatches\}/); assert.match(source, /Batch preview/); assert.match(source, /Enter a value to preview this policy/); assert.match(source, /entry\.unitCost/); assert.doesNotMatch(source, /providerPrice=\{providerPrice\}/); });
test("commercial prices expose current receipt layers as visible responsive Batches", async () => { const source = await readFile(component, "utf8"); assert.match(source, /sellingPolicy\?\.availableBatches/); assert.match(source, /inventory-batch-list/); assert.match(source, /function BatchRow/); assert.doesNotMatch(source, /Available FCFS batches/); assert.match(source, /batch\.receiptReference/); assert.match(source, /batch\.availableQuantity/); assert.match(source, /batch\.reservedQuantity/); assert.match(source, /batch\.unitCost === null \? "Unknown"/); assert.match(source, /isNextToUse=\{index === 0\}/); assert.match(source, />Next to use</); });
test("batches show their exact stored positions and label unresolved legacy placement", async () => { const source = await readFile(component, "utf8"); assert.match(source, />Stored at</); assert.match(source, /batch\.placements\?\.length/); assert.match(source, /batchPositionLabel/); assert.match(source, /Position not linked/); assert.match(source, /Reconcile this legacy batch/); assert.match(source, /batch\.placementStatus === "partial"/); });
test("stock batches expose an audited cost correction editor", async () => { const source = await readFile(component, "utf8"); assert.match(source, /function BatchCostEditor/); assert.match(source, /expectedVersion: Number\(batch\.costVersion \|\| 0\)/); assert.match(source, /Why is this cost changing\?/); assert.match(source, /existing Workorder price snapshots stay unchanged/); assert.match(source, /\/api\/office\/inventory\/batches\/\$\{encodeURIComponent\(batch\.costLayerId\)\}\/cost/); assert.match(source, /canEditBatchCost/); assert.match(source, /batch\.unitCost === null \? "Add cost" : "Edit cost"/); });
test("commercial editor and history tracks stay contained by the detail pane", async () => { const source = await readFile(styles, "utf8"); assert.match(source, /\.inventory-commercial-price-fields \{[^}]*min-width: 0;[^}]*max-width: 100%;[^}]*\}/s); assert.match(source, /\.inventory-commercial-history, \.inventory-commercial-configured-history \{ min-width: 0; max-width: 100%; \}/); assert.match(source, /\.inventory-commercial-history-table \{[^}]*width: 100%;[^}]*min-width: 0;[^}]*max-width: 100%;[^}]*\}/s); assert.match(source, /\.inventory-commercial-history-table \.operational-data-table \{ min-width: 0; table-layout: fixed; \}/); });
test("location commercial and selling policy requests carry the selected location scope", async () => { const source = await readFile(component, "utf8"); assert.match(source, /params\.set\("locationId", locationId\)/); assert.match(source, /new URLSearchParams\(\{ locationId \}\)/); assert.match(source, /selling-policy\$\{policyParams\}/); assert.match(source, /expectedVersion: Number\(writeVersion\)/); assert.match(source, /writeVersion=\{details\.sellingPolicy\?\.writeVersion\}/); assert.match(source, /\[part\?\.catalogPartId, locationId\]/); assert.match(source, /sequence\.current \+= 1/); });
test("selling policy saves a versioned idempotent command and keeps receipt evidence read only", async () => { const source = await readFile(component, "utf8"); assert.match(source, /icon=\{RefreshCw01\}/); assert.match(source, /onClick=\{\(\) => load\(\{ preserveError: true \}\)\}/); assert.match(source, /if \(!preserveError\) setError\(""\)/); assert.ok(source.indexOf("if (error && !details)") < source.indexOf("if (loading && !details)")); assert.match(source, /loading \? "Refreshing…" : "Refresh"/); assert.doesNotMatch(source, />Try again</); assert.match(source, /idempotencyKey: newKey\("selling-policy"\)/); assert.match(source, /reason: `Updated \$\{label\.toLowerCase\(\)\}`/); assert.match(source, /disabled=\{!dirty \|\| !valid \|\| busy \|\| disabled\}/); assert.doesNotMatch(source, /tax-profiles\?companyId=/); assert.doesNotMatch(source, />Tax profiles</); assert.doesNotMatch(source, />Calculate</); assert.doesNotMatch(source, />Tax treatment</); assert.doesNotMatch(source, /inventory-commercial-reason/); assert.match(source, /invoiceRun: entry\.invoiceRunId \|\| entry\.source\.id/); assert.match(source, /displayMoney\(entry\.unitCost, entry\.currency\)/); });
