import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

const component = new URL("./PartCommercialDetails.jsx", import.meta.url);
const styles = new URL("./part-commercial-details.css", import.meta.url);
test("commercial prices keep inline selling and internal editors above purchase evidence", async () => { const source = await readFile(component, "utf8"); assert.doesNotMatch(source, /<h3>\{locationId \? "Prices" : "Company prices"\}<\/h3>/); assert.match(source, /Latest purchase cost/); assert.match(source, /Purchase history/); assert.match(source, /inventory-commercial-editors/); assert.match(source, /aria-label=\{`\$\{label\} amount`\}/); assert.match(source, /<CurrencySelector/); assert.match(source, /type="submit" variant="primary"/); assert.ok(source.indexOf('editor("selling", "Selling price")') < source.indexOf("Latest purchase cost")); assert.ok(source.indexOf('editor("internal", "Internal price")') < source.indexOf("Latest purchase cost")); assert.match(source, /priceSourceLabel\(source\)/); assert.match(source, /locationPriceEditState\(projection\)/); assert.match(source, /prices\.override\?\.history/); assert.match(source, /prices\.companyDefault\?\.history/); assert.match(source, /Company price defaults/); assert.match(source, /costs\.truncated/); });

test("commercial prices show read-only Odoo purchase-order evidence", async () => { const source = await readFile(component, "utf8"); assert.match(source, /details\.purchaseOrders/); assert.match(source, /Latest Odoo PO price/); assert.match(source, />Odoo purchase orders</); assert.match(source, /entry\.orderNumber/); assert.match(source, /entry\.vendorName/); assert.match(source, /entry\.receivedQuantity/); });

test("commercial editors show Odoo catalog prices as references without pre-filling local decisions", async () => { const source = await readFile(component, "utf8"); assert.match(source, /details\.odooPrices/); assert.match(source, /Odoo reference:/); assert.match(source, /providerPrice=\{providerPrice\}/); });
test("commercial editor and history tracks stay contained by the detail pane", async () => { const source = await readFile(styles, "utf8"); assert.match(source, /\.inventory-commercial-price-fields \{[^}]*min-width: 0;[^}]*max-width: 100%;[^}]*\}/s); assert.match(source, /\.inventory-commercial-history, \.inventory-commercial-configured-history \{ min-width: 0; max-width: 100%; \}/); assert.match(source, /\.inventory-commercial-history-table \{[^}]*width: 100%;[^}]*min-width: 0;[^}]*max-width: 100%;[^}]*\}/s); assert.match(source, /\.inventory-commercial-history-table \.operational-data-table \{ min-width: 0; table-layout: fixed; \}/); });
test("location commercial requests use the scoped read, preview and write paths", async () => { const source = await readFile(component, "utf8"); assert.match(source, /params\.set\("locationId", locationId\)/); assert.match(source, /`\/locations\/\$\{encodeURIComponent\(locationId\)\}`/); assert.match(source, /expectedVersion: expectedVersion \?\? editView\.version/); assert.match(source, /\[part\?\.catalogPartId, locationId\]/); assert.match(source, /sequence\.current \+= 1/); });
test("commercial editors save changed inline values with generated audit evidence", async () => { const source = await readFile(component, "utf8"); assert.match(source, /icon=\{RefreshCw01\}/); assert.match(source, /onClick=\{\(\) => load\(\{ preserveError: true \}\)\}/); assert.match(source, /if \(!preserveError\) setError\(""\)/); assert.ok(source.indexOf("if (error && !details)") < source.indexOf("if (loading && !details)")); assert.match(source, /loading \? "Refreshing…" : "Refresh"/); assert.doesNotMatch(source, />Try again</); assert.match(source, /setKey\(newKey\(`part-price-\$\{kind\}`\)\)/); assert.match(source, /idempotencyKey: key \|\| newKey/); assert.match(source, /`Updated \$\{label\.toLowerCase\(\)\}`/); assert.match(source, /`Cleared \$\{label\.toLowerCase\(\)\}`/); assert.match(source, /disabled=\{!dirty \|\| !valid \|\| busy \|\| disabled\}/); assert.match(source, /taxTreatment: "not_configured"/); assert.match(source, /taxProfileVersionId: null/); assert.doesNotMatch(source, /tax-profiles\?companyId=/); assert.doesNotMatch(source, />Tax profiles</); assert.doesNotMatch(source, />Calculate</); assert.doesNotMatch(source, />Tax treatment</); assert.doesNotMatch(source, />Change<\/Button>/); assert.doesNotMatch(source, /inventory-commercial-reason/); assert.match(source, /invoiceRun: entry\.invoiceRunId \|\| entry\.source\.id/); assert.match(source, /displayMoney\(entry\.unitCost, entry\.currency\)/); });
