import test from "node:test";
import assert from "node:assert/strict";
import { handleInspectionsApi } from "./inspections.routes.js";

function harness(body={}){const sent=[];return{sent,helpers:{requestContext:{actor:{id:"u"}},readBody:async()=>body,sendJson:(_res,status,payload)=>sent.push({status,payload}),sendPdfBytes:(_res,bytes,fileName)=>sent.push({status:200,bytes,fileName})}};}
test("route validates and delegates idempotent weekly inspection creation",async()=>{const input={companyId:"11111111-1111-4111-8111-111111111111",locationId:"22222222-2222-4222-8222-222222222222",assetId:"33333333-3333-4333-8333-333333333333",mechanicUserIds:[],idempotencyKey:"inspection-create-001"};const h=harness(input);let received;assert.equal(await handleInspectionsApi({method:"POST"},{},new URL("http://x/api/inspections"),h.helpers,{request:async(_context,value)=>(received=value,{id:"i"})}),true);assert.equal(h.sent[0].status,201);assert.equal(received.officeInstructions,"");assert.equal(received.idempotencyKey,"inspection-create-001");});
test("route rejects inspection creation without an idempotency key",async()=>{const h=harness({companyId:"11111111-1111-4111-8111-111111111111",locationId:"22222222-2222-4222-8222-222222222222",assetId:"33333333-3333-4333-8333-333333333333",mechanicUserIds:[]});await assert.rejects(handleInspectionsApi({method:"POST"},{},new URL("http://x/api/inspections"),h.helpers,{request:async()=>assert.fail()}),/expected string|required/i);});
test("route rejects any inspection type choice including annual",async()=>{const h=harness({companyId:"11111111-1111-4111-8111-111111111111",locationId:"22222222-2222-4222-8222-222222222222",assetId:"33333333-3333-4333-8333-333333333333",idempotencyKey:"inspection-create-annual",inspectionType:"annual"});await assert.rejects(handleInspectionsApi({method:"POST"},{},new URL("http://x/api/inspections"),h.helpers,{request:async()=>assert.fail()}),/Unrecognized key|unrecognized/i);});
test("route parses bounded cursor list without loading detail",async()=>{const h=harness();let value;await handleInspectionsApi({method:"GET"},{},new URL("http://x/api/inspections?status=completed&limit=20&search=T12"),h.helpers,{list:async(_context,input)=>(value=input,{items:[],nextCursor:null})});assert.equal(value.limit,20);assert.equal(value.status,"completed");assert.equal(h.sent[0].status,200);});
test("route accepts the bounded not_completed status contract",async()=>{const h=harness();let value;await handleInspectionsApi({method:"GET"},{},new URL("http://x/api/inspections?status=not_completed"),h.helpers,{list:async(_context,input)=>(value=input,{items:[],nextCursor:null})});assert.equal(value.status,"not_completed");assert.equal(h.sent[0].status,200);});
test("workorder inspection context route validates identity and returns all source choices",async()=>{const workorderId="44444444-4444-4444-8444-444444444444";const h=harness();let received;const payload={inspectionContext:{workorderId,sources:[{inspectionId:"new"},{inspectionId:"old"}]}};await handleInspectionsApi({method:"GET"},{},new URL(`http://x/api/inspections/workorders/${workorderId}/context`),h.helpers,{workorderContext:async(_context,id)=>(received=id,payload)});assert.equal(received,workorderId);assert.deepEqual(h.sent[0],{status:200,payload});const invalid=harness();await assert.rejects(handleInspectionsApi({method:"GET"},{},new URL("http://x/api/inspections/workorders/not-a-uuid/context"),invalid.helpers,{workorderContext:async()=>assert.fail()}),/uuid|invalid/i);});
test("response route requires expected version and issue details",async()=>{const h=harness({expectedVersion:2,responses:[{itemKey:"brakes",response:"issue"}]});await assert.rejects(handleInspectionsApi({method:"PATCH"},{},new URL("http://x/api/inspections/i/responses"),h.helpers,{responses:async()=>assert.fail()}),/severity|finding|Issue/i);});
test("start route requires review evidence, accepts bounded readings, and rejects location re-entry",async()=>{const valid=harness({expectedVersion:2,odometerMiles:123456.7,engineHours:8901.2,previousReportReviewed:true});let received;await handleInspectionsApi({method:"POST"},{},new URL("http://x/api/inspections/i/actions/start"),valid.helpers,{start:async(_context,id,input)=>(received={id,input},{id})});assert.equal(received.input.odometerMiles,123456.7);assert.equal(received.input.previousReportReviewed,true);const missing=harness({expectedVersion:2,odometerMiles:1});await assert.rejects(handleInspectionsApi({method:"POST"},{},new URL("http://x/api/inspections/i/actions/start"),missing.helpers,{start:async()=>assert.fail()}),/boolean|required|expected/i);const override=harness({expectedVersion:2,odometerMiles:1,previousReportReviewed:false,locationId:"22222222-2222-4222-8222-222222222222"});await assert.rejects(handleInspectionsApi({method:"POST"},{},new URL("http://x/api/inspections/i/actions/start"),override.helpers,{start:async()=>assert.fail()}),/unrecognized/i);});
test("assignment, eligible workorders, link, and archive routes use narrow validated contracts", async () => {
  const h = harness({ expectedVersion:2, mechanicUserIds:["33333333-3333-4333-8333-333333333333"] });
  let assignment;
  await handleInspectionsApi({method:"POST"},{},new URL("http://x/api/inspections/i/assignments"),h.helpers,{assign:async(_context,id,input) => (assignment={id,input},{id})});
  assert.equal(assignment.id,"i"); assert.equal(assignment.input.expectedVersion,2);
  const lookup=harness(); await handleInspectionsApi({method:"GET"},{},new URL("http://x/api/inspections/i/workorders?search=WO&limit=3"),lookup.helpers,{eligibleWorkorders:async(_context,id,input) => ({items:[{id,input}]})});
  assert.deepEqual(lookup.sent[0].payload.items[0].input,{search:"WO",limit:3});
  const link=harness({expectedVersion:3,workorderId:"44444444-4444-4444-8444-444444444444",idempotencyKey:"inspection-link-001"}); let linked;
  await handleInspectionsApi({method:"POST"},{},new URL("http://x/api/inspections/i/findings/f/workorder-links"),link.helpers,{link:async(_context,id,findingId,input) => (linked={id,findingId,input},{id})});
  assert.equal(linked.findingId,"f"); assert.equal(linked.input.workorderId,"44444444-4444-4444-8444-444444444444");
  const archive=harness({idempotencyKey:"inspection-print-001"}); await handleInspectionsApi({method:"POST"},{},new URL("http://x/api/inspections/i/print-archives"),archive.helpers,{createArchive:async()=>({archive:{id:"a"}})});
  assert.equal(archive.sent[0].status,201);
  const pdf=harness();await handleInspectionsApi({method:"GET"},{},new URL("http://x/api/inspections/i/print-archives/a/pdf"),pdf.helpers,{readArchivePdf:async()=>({bytes:Buffer.from("%PDF-test"),fileName:"INS-1.pdf"})});
  assert.equal(pdf.sent[0].fileName,"INS-1.pdf");assert.equal(pdf.sent[0].bytes.subarray(0,5).toString(),"%PDF-");
});

test("typed correction, reinspection, and atomic finding-workorder routes use distinct contracts", async () => {
  const correction=harness({expectedVersion:3,reason:"Correct a recorded finding",changes:{finalNotes:"Corrected"},idempotencyKey:"inspection-correction-001"}); let corrected;
  await handleInspectionsApi({method:"POST"},{},new URL("http://x/api/inspections/i/actions/correct"),correction.helpers,{correct:async(_context,id,input)=>(corrected={id,input},{id:"correction"})});
  assert.equal(corrected.id,"i");assert.equal(corrected.input.changes.finalNotes,"Corrected");assert.equal(correction.sent[0].status,201);
  const reinspection=harness({expectedVersion:3,reason:"Verify completed repair",mechanicUserIds:[],idempotencyKey:"inspection-reinspect-001"});let reinspected;
  await handleInspectionsApi({method:"POST"},{},new URL("http://x/api/inspections/i/actions/reinspect"),reinspection.helpers,{reinspect:async(_context,id,input)=>(reinspected={id,input},{id:"reinspection"})});
  assert.equal(reinspected.input.startImmediately,false);assert.equal(reinspection.sent[0].status,201);
  const invalidSelfStart=harness({expectedVersion:3,reason:"Verify completed repair",mechanicUserIds:[],startImmediately:true,idempotencyKey:"inspection-reinspect-invalid"});await assert.rejects(handleInspectionsApi({method:"POST"},{},new URL("http://x/api/inspections/i/actions/reinspect"),invalidSelfStart.helpers,{reinspect:async()=>assert.fail()}),/false|literal|invalid/i);
  const create=harness({expectedVersion:3,findingIds:["44444444-4444-4444-8444-444444444444"],idempotencyKey:"inspection-create-001"}); let received;
  await handleInspectionsApi({method:"POST"},{},new URL("http://x/api/inspections/i/workorders"),create.helpers,{createWorkorder:async(_context,id,input)=>(received={id,input},{workorderId:"w"})});
  assert.equal(received.id,"i"); assert.deepEqual(received.input.findingIds,["44444444-4444-4444-8444-444444444444"]); assert.equal(create.sent[0].status,201);
  const legacy=harness({expectedVersion:3,reason:"Ambiguous",idempotencyKey:"inspection-revision-old"});assert.equal(await handleInspectionsApi({method:"POST"},{},new URL("http://x/api/inspections/i/revisions"),legacy.helpers,{}),false);
});

test("completion route carries explicit Admin inspector attestation",async()=>{const h=harness({expectedVersion:4,finalNotes:"Done",actingAsInspector:true});let received;await handleInspectionsApi({method:"POST"},{},new URL("http://x/api/inspections/i/actions/complete"),h.helpers,{complete:async(_context,id,input)=>(received={id,input},{id})});assert.equal(received.input.actingAsInspector,true);});

test("completed finding follow-up routes require versioned idempotent contracts",async()=>{const findingId="44444444-4444-4444-8444-444444444444";const link=harness({expectedVersion:1,workorderId:"55555555-5555-4555-8555-555555555555",idempotencyKey:"follow-up-link-001"});let linked;await handleInspectionsApi({method:"POST"},{},new URL(`http://x/api/inspections/i/follow-ups/${findingId}/actions/link-workorder`),link.helpers,{linkFollowUp:async(_context,id,finding,input)=>(linked={id,finding,input},{inspection:{id}})});assert.equal(linked.finding,findingId);assert.equal(linked.input.expectedVersion,1);const create=harness({expectedVersion:1,idempotencyKey:"follow-up-create-001",concern:"Repair tire"});await handleInspectionsApi({method:"POST"},{},new URL(`http://x/api/inspections/i/follow-ups/${findingId}/actions/create-workorder`),create.helpers,{createFollowUpWorkorder:async()=>({inspection:{id:"i"},workorderId:"w"})});assert.equal(create.sent[0].status,201);const noWorkorder=harness({expectedVersion:1,idempotencyKey:"follow-up-none-001",reason:"Observed condition is acceptable"});await handleInspectionsApi({method:"POST"},{},new URL(`http://x/api/inspections/i/follow-ups/${findingId}/actions/no-workorder`),noWorkorder.helpers,{noWorkorderFollowUp:async()=>({inspection:{id:"i"}})});assert.equal(noWorkorder.sent[0].status,200);});
