import { getVehicleLocation } from "../../components/workorders/AssetLocationCard.jsx";
import { interfaceText } from "../../i18n/index.js";
import { WorkorderDetailModuleHost } from "../workorder-modules/WorkorderDetailModuleHost.jsx";
import { workorderNeedsChatAttention } from "./workorder-detail-sections.js";

export function WorkorderDetailSections({
  activeWorkorder,
  actorId,
  actorRole,
  assignedMechanicIds,
  conversationMessages,
  detailMechanicNames,
  detailSection,
  detailSections = [],
  detailStatus,
  filledPartCount,
  form,
  isCompact,
  isMechanicDetail,
  isOfficeDetail,
  locale = "en",
  mapsConfig,
  mechanicAction,
  mechanicMapLocation,
  mechanicMapVehicle,
  mechanicProgress,
  mechanicValidationField = "",
  modulePolicies = {},
  officeAssignment,
  officeAssignmentChanged,
  officeDetailState,
  officeLocations,
  odooController,
  pendingPartCount,
  selectedVehicle,
  vehicleLookup,
  visibleTimeline,
  workorderChatContent,
  applyVehicle,
  reloadActiveWorkorder,
  saveActiveUsedParts,
  saveOfficeWorkorder,
  openOfficeCancel,
  openOfficeReturn,
  selectOfficeLocation,
  setDetailSection,
  setOfficeAssignment,
  updateActiveUsedParts,
  updateActiveLaborHours,
  updateField,
  updateOfficeMechanicTeam,
  updateStartDate,
  updateUnitNumber,
  unitHistoryController,
  vehicleMileage,
  vehicleModelText,
  acceptOpenedMechanicWorkorder,
  markOfficeWorkorderDone,
  openOfficeClose,
  openMechanicFinish,
}) {
  const t = (key) => interfaceText(locale, key);
  const detailMapVehicle = selectedVehicle || mechanicMapVehicle;
  const detailMapLocation = getVehicleLocation(selectedVehicle) || mechanicMapLocation;
  const missingInfoAttention = (activeWorkorder.activeAttention || []).find((entry) => entry.reason === "missing_info");
  const moduleProps = {
    activity: {
      activeWorkorder,
      detailSection,
      isMechanicDetail,
      onSelect: setDetailSection,
      visibleTimeline,
    },
    assignment: {
      activeSection: detailSection,
      allowedActions: activeWorkorder.allowedActions,
      assignedIds: assignedMechanicIds,
      assignment: officeAssignment,
      assignmentChanged: officeAssignmentChanged,
      assignableMechanics: activeWorkorder.assignableMechanics || [],
      busy: officeDetailState.busy,
      mechanicNames: detailMechanicNames,
      onAssignmentChange: setOfficeAssignment,
      onSave: updateOfficeMechanicTeam,
      onSelect: setDetailSection,
    },
    chat: {
      activeWorkorder,
      attention: workorderNeedsChatAttention(detailStatus),
      conversationMessages,
      detailSection,
      isCompact,
      isMechanicDetail,
      label: isMechanicDetail ? t("detail.help") : "Chat",
      onSelect: setDetailSection,
      content: workorderChatContent,
    },
    completion: {
      activeSection: detailSection,
      allowedActions: activeWorkorder.allowedActions,
      busy: Boolean(mechanicAction?.busy || officeDetailState.busy),
      customerSignature: form.customerSignature,
      message: officeDetailState.error ? "" : officeDetailState.message,
      onAccept: acceptOpenedMechanicWorkorder,
      onApprove: openOfficeClose,
      onCancel: openOfficeCancel,
      onMarkDone: isOfficeDetail ? markOfficeWorkorderDone : openMechanicFinish,
      onRequestChanges: openOfficeReturn,
      onSelect: setDetailSection,
      workorder: { ...activeWorkorder.workorder, formData: form },
    },
    concern: {
      activeSection: detailSection,
      activeWorkorder,
      allowedActions: activeWorkorder.allowedActions,
      concern: form.mechanicConcern,
      busy: officeDetailState.busy,
      message: officeDetailState.error ? "" : officeDetailState.message,
      missingInfoAttention: Boolean(missingInfoAttention),
      missingInfoNote: missingInfoAttention?.details?.note || missingInfoAttention?.note || activeWorkorder.workorder.missingInfoNote || "Surveillance requested more information.",
      onChange: (value) => updateField("mechanicConcern", value),
      officeNotes: form.officeNotes,
      onOfficeNotesChange: (value) => updateField("officeNotes", value),
      onSave: saveOfficeWorkorder,
      onSelect: setDetailSection,
    },
    diagnosisRepair: {
      activeSection: detailSection,
      allowedActions: activeWorkorder.allowedActions,
      diagnosis: form.diagnosis,
      localeText: t,
      mechanicProgress: isMechanicDetail ? mechanicProgress : null,
      validationField: isMechanicDetail ? mechanicValidationField : "",
      onChange: updateField,
      onSelect: setDetailSection,
      workPerformed: form.workPerformed,
    },
    location: {
      activeSection: detailSection,
      allowedActions: activeWorkorder.allowedActions,
      location: activeWorkorder.workorder.location,
      locations: officeLocations,
      mapLocation: detailMapLocation,
      mapsConfig,
      onChange: selectOfficeLocation,
      onSelect: setDetailSection,
      vehicle: detailMapVehicle,
    },
    odoo: {
      activeWorkorder,
      controller: odooController,
      detailSection,
      detailStatus,
      fieldAccess: {
        concern: modulePolicies.concern?.canRead,
        diagnosisRepair: modulePolicies.diagnosisRepair?.canRead,
      },
      onSelect: setDetailSection,
    },
    parts: {
      activeWorkorder,
      actorId,
      detailSection,
      filledPartCount,
      form,
      isMechanicDetail,
      isOfficeDetail,
      locale,
      pendingPartCount,
      onChanged: () => reloadActiveWorkorder({
        preserveForm: Boolean(isMechanicDetail && mechanicProgress?.hasUnsyncedChanges),
      }),
      onPartsChange: updateActiveUsedParts,
      onLaborHoursChange: updateActiveLaborHours,
      onLaborRepairOrderChange: (value) => updateField("workPerformed", value),
      onSaveParts: saveActiveUsedParts,
      onSelect: setDetailSection,
    },
    photos: { activeSection: detailSection, messages: conversationMessages, onSelect: setDetailSection },
    schedule: {
      activeSection: detailSection,
      allowedActions: activeWorkorder.allowedActions,
      endDate: form.workEndDate,
      locale,
      onChange: updateField,
      onSelect: setDetailSection,
      onStartDateChange: updateStartDate,
      startDate: form.workStartDate,
      workorder: activeWorkorder.workorder,
    },
    unit: {
      activeWorkorder,
      actorRole,
      detailSection,
      form,
      historyController: unitHistoryController,
      onApplyVehicle: applyVehicle,
      onFieldChange: updateField,
      onSelect: setDetailSection,
      onUnitNumberChange: updateUnitNumber,
      vehicleLookup,
      vehicleMileage,
      vehicleModelText,
    },
  };

  return <WorkorderDetailModuleHost sections={detailSections} moduleProps={moduleProps} />;
}
